- platform: wake_on_lan
  mac: "D4-3D-7E-BA-A6-EF"
  name: Neo
  host: "192.168.1.128"
- platform: wake_on_lan
  mac: "70-8B-CD-58-66-D5"
  name: Trinity
  host: "192.168.1.250"

# - platform: template
  # switches:
    # home_lights:
      # value_template: "{{ is_state('sensor.skylight', 'on') }}"
      # turn_on:
        # service: homeassistant.turn_on
        # entity_id: all
        # data:
          # area_id: living_room, kitchen, dining_room, bedroom, office
      # turn_off:
        # service: homeassistant.turn_off
        # entity_id: all
        # data:
          # area_id: living_room, kitchen, dining_room, bedroom, office