dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7.6"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis_zones.yaml zones.yaml
  - mv travis/google_service_account.json google_service_account.json
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
