language: python
python:
  - "3.6"
before_install:
  - mv travis/travis_secrets.yaml secrets.yaml
  - mv travis/travis_zones.yaml zones.yaml
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
