- alias: 'Sunrise'
  trigger:
    platform: sun
    event: sunrise
#    offset: '+00:15:00'
  action:
    - service: notify.pushbullet
      data:
        message: 'The sun is up.'
    - service: switch.turn_off
      entity_id: group.home_lights

- alias: 'Get Up'
  trigger:
    platform: time
    after: '07:00:00'
  condition:
    condition: and
    conditions:
      # - condition: state
        # entity_id: sun.sun
        # state: 'below_horizon'
      - condition: time
        weekday:
          - mon
          - tue
          - wed
          - thu
          - fri
  action:
    - service: switch.turn_on
      entity_id: group.home_lights
    - service: notify.pushbullet
      data:
        message: 'Time to start the day!'

#- alias: 'See You Later'
#  trigger:
#    platform: state
#    entity_id: device_tracker.peter_gs7 #group.family
#    from: 'home'
#    to: 'not_home'
#  condition:
#    condition: sun
#    after: sunset
#    after_offset: '-00:30:00'
#  action:
#    - service: switch.turn_off
#      entity_id: group.all_switches
#    - service: notify.pushbullet
#      data:
#        message: 'See you later!'

#- alias: 'Welcome Home'
#  trigger:
#    platform: state
#    entity_id: device_tracker.peter_gs7 #group.family
#    from: 'not_home'
#    to: 'home'
#    for:
#      minutes: 10
#  condition:
#    condition: sun
#    after: sunset
#    after_offset: '-00:30:00'
#  action:
#    - service: switch.turn_on
#      entity_id: group.living_room_lights
#    - service: notify.pushbullet
#      data:
#        message: 'Welcome Home!'

- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.peter_gs7 #group.family
        state: 'home'
      - condition: time
        before: '22:00:00'
  action:
    - service: notify.pushbullet
      data:
        message: 'The sun is down.'
    - service: switch.turn_on
      entity_id: group.living_room_lights

- alias: 'Goodnight'
  trigger:
    platform: time
    after: '23:05:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri  
  action:
    - service: switch.turn_off
      entity_id: group.home_lights
    - service: notify.pushbullet
      data:
        message: 'Goodnight!'

- alias: 'Computer On'
  trigger:
    platform: state
    entity_id: switch.neo
    from: 'off'
    to: 'on'
    # for:
      # minutes: 1
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:00:00'
      - condition: sun
        after: sunset
        after_offset: '-00:15:00'
  action:
    - service: switch.turn_on
      entity_id: group.office_lights

# - alias: 'Computer Off'
  # trigger:
    # platform: state
    # entity_id: switch.neo
    # from: 'on'
    # to: 'off'
    # for:
      # minutes: 1
  # condition:
    # condition: sun
    # after: sunset
    # after_offset: '-00:30:00'
  # action:
    # - service: switch.turn_off
      # entity_id: group.office_lights

#- alias: "Media player paused/stopped"
#  trigger:
#    - platform: state
#      entity_id: media_player.living_room
#      from: 'playing'
#  condition:
#    - condition: state
#      entity_id: sun.sun
#      state: 'below_horizon'
#  action:
#    - service: switch.turn_on
#      entity_id: group.living_room_lights

- alias: "Media player playing"
  trigger:
    - platform: state
      entity_id: media_player.living_room
      to: 'playing'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: switch.turn_off
      entity_id: group.living_room_lights

- alias: "Update Available"
  trigger:
    - platform: state
      entity_id: updater.updater
  action:
    - service: notify.pushbullet
      data:
        title: 'New Home Assistant Release'
        message: "Home Assistant {{ states.updater.updater.state }} is now available"
        
- alias: "NextTrain_DC"
  trigger:
    - platform: state
      entity_id: input_boolean.wmata_dc
      state: 'on'
  action:
    - service: tts.google_say
      data_template:
        cache: false
        entity_id: media_player.google_home
        message: "the next metro train leaves for DC from friendship heights in {{ states('sensor.wmata_dc') }} minutes"
    - service: input_boolean.turn_off
      entity_id: input_boolean.wmata_dc
        
- alias: "NextTrain_MD"
  trigger:
    - platform: state
      entity_id: input_boolean.wmata_md
      state: 'on'
  action:
    - service: tts.google_say
      data_template:
        cache: false
        entity_id: media_player.google_home
        message: "the next metro train leaves for Maryland from friendship heights in {{ states('sensor.wmata_md') }} minutes"
    - service: input_boolean.turn_off
      entity_id: input_boolean.wmata_md