- alias: Sunrise
  id: sunrise
  trigger:
    platform: sun
    event: sunrise
  action:
  - service: notify.pushbullet
    data:
      message: The sun is up.
- alias: Wake Up
  id: wake_up
  trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == states(''sensor.alarm_time'') }}'
  condition:
    condition: or
    conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'on'
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.alarmweekday
      state: 'off'
  action:
  - service: switch.turn_on
    entity_id: switch.bedroom_peter_light
  - service: notify.pushbullet
    data:
      message: Time to start the day!
  - delay: 00:45:00
  - service: switch.turn_off
    entity_id: switch.bedroom_peter_light
- alias: See You Later
  id: later
  trigger:
  - platform: state
    entity_id: group.family
    to: not_home
    for:
      minutes: 10
  - platform: state
    entity_id: alarm_control_panel.10th_street
    to: armed_home
  - platform: state
    entity_id: alarm_control_panel.10th_street
    to: armed_away
  action:
  - service: homeassistant.turn_off
    entity_id: group.home_lights
  - service: notify.pushbullet
    data:
      message: See you later!
- alias: Welcome Home
  id: home
  trigger:
  - platform: state
    entity_id: group.family
    from: not_home
    to: home
    for:
      minutes: 1
  - platform: state
    entity_id: alarm_control_panel.10th_street
    to: disarmed
  action:
  - service: notify.pushbullet
    data:
      message: Welcome Home!
- id: sunset
  alias: Sunset
  trigger:
  - event: sunset
    platform: sun
  action:
  - data:
      message: The sun is down.
    service: notify.pushbullet
- alias: Goodnight Work Night
  id: goodnight-work
  trigger:
    platform: time
    at: '23:05:00'
  condition:
  - condition: state
    entity_id: binary_sensor.worknight
    state: 'on'
  action:
  - service: homeassistant.turn_off
    entity_id: group.home_lights, group.patio_lights, group.holiday_lights
  - service: notify.pushbullet
    data:
      message: Goodnight!
- alias: Goodnight Leisure Night
  id: goodnight-leisure
  trigger:
    platform: time
    at: 01:05:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday
    state: 'off'
  action:
  - service: homeassistant.turn_off
    entity_id: group.home_lights, group.patio_lights, group.holiday_lights
  - service: notify.pushbullet
    data:
      message: Goodnight!
- id: fan
  alias: Fan
  trigger:
  - minutes: /60
    platform: time_pattern
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: group.family
      state: home
  action:
  - alias: ''
    data:
      entity_id: fan.hvac_fan
    service: fan.turn_on
