- platform: workday
  name: "Workday"
  country: US
  workdays: [mon,tue,wed,thu,fri]
  excludes: [sat,sun,holiday]
#  add_holidays: ['']
- platform: workday
  name: "Worknight"
  days_offset: 1
  country: US
  workdays: [mon,tue,wed,thu,fri]
  excludes: [sat,sun,holiday]
#  add_holidays: ['']

- platform: template
  sensors:
    smoke_alarm:
      entity_id: sensor.ecolink_firefighter_smoke_detector
      friendly_name: "Smoke Alarm"
      device_class: smoke
      value_template: "{{ is_state('sensor.ecolink_firefighter_smoke_detector', 'detected') }}"
    co_alarm:
      entity_id: sensor.firefighter_carbon_monoxide_detector
      friendly_name: "CO Alarm"
      device_class: safety
      value_template: "{{ is_state('sensor.ecolink_firefighter_carbon_monoxide_detector', 'detected') }}"

- platform: template
  sensors:
    recycle:
      entity_id:
        - calendar.recycle
        - sensor.time
      friendly_name: "Recycle"
      icon_template: mdi:recycle
      value_template: >
        {% set e = strptime(
             states.calendar.recycle.attributes.start_time,
             '%Y-%m-%d %H:%M:%S') %}
        {{ e.strftime('%j')|int - now().strftime('%j')|int == 1 and now().hour >= 12 }}
    trash:
      entity_id:
        - calendar.trash
        - sensor.time
      friendly_name: "Trash"
      icon_template: >-
        {% if is_state("binary_sensor.trash", "on") %}
          mdi:delete
        {% else %}
          mdi:delete-outline
        {% endif %}
      value_template: >
        {% set e = strptime(
             states.calendar.trash.attributes.start_time,
             '%Y-%m-%d %H:%M:%S') %}
        {{ e.strftime('%j')|int - now().strftime('%j')|int == 1 and now().hour >= 12 }}

- platform: template
  sensors:
    washer_status:
        friendly_name: "Washer Cycle"
        value_template: "{{ states('sensor.washer_power')|float > 5 }}"
        icon_template: mdi:washing-machine
        delay_on:
          minutes: 10
        delay_off:
          minutes: 3
    dryer_status:
        friendly_name: "Dryer Cycle"
        value_template: "{{ states('sensor.dryer_power')|float > 5 }}"
        icon_template: mdi:tumble-dryer
        delay_on:
          minutes: 10
        delay_off:
          minutes: 3