homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 87
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ssl_certificate: !secret ssl_cert_loc
  ssl_key: !secret ssl_key_loc

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google

#media players
media_player:
  - platform: plex

#device tracking
device_tracker:
  - platform: automatic
    client_id: c1ce08e5c7825763112b
    secret: !secret automatic_secret
    username: pae2008@gmail.com
    password: !secret automatic_password
  - platform: nmap_tracker
#    hosts: 192.168.1.28 192.168.1.128
    hosts: 192.168.1.1-254
    home_interval: 10
    scan_options: "-PS135,445 -F --host-timeout 5s"

ifttt:
  key: !secret ifttt_key

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

automation: !include automation.yaml
zone: !include zones.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml

#scene: !include scenes.yaml #not sure how these are different from automations
