homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 87
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert_loc
  ssl_key: !secret ssl_key_loc

# Checks for available updates
updater:

# Discover some devices automatically
#discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: 'en-us'

config:
map:

mqtt:
  client_id: 8315
  
#media players
media_player:
  - platform: plex
  - platform: cast
    host: 192.168.1.80
  - platform: cast
    host: 192.168.1.81
  - platform: roku
    host: 192.168.1.82
  - platform: cast
    host: 192.168.1.83
  - platform: cast
    host: 192.168.1.84

#device tracking
device_tracker:
  - platform: automatic
    client_id: c1ce08e5c7825763112b
    secret: !secret automatic_secret
    current_location: true
  # - platform: nmap_tracker
    # hosts:
    # - 192.168.1.1-30
    # - 192.169.1.128
    # - 192.168.1.42
    # - 192.168.1.200
    # home_interval: 5
    # scan_options: "-PS135,445 -F --host-timeout 5s"
    # exclude:
    # - 192.168.1.150
    # - 192.168.1.100
    # - 192.168.1.101
  - platform: linksys_smart
    host: 192.168.1.1

recorder:
  exclude:
    domains:
    entities:
      - sensor.internet_time
      - sensor.wmata_dc
      - sensor.wmata_md
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
      - sensor.time
      - sensor.date
      - sensor.time_utc
      - sensor.time_beat
      - switch.cable_hd
      - switch.cable_1
      - switch.cable_2
      - switch.cable_3
      - switch.cable_4
      - switch.cable_5
      - switch.cable_6
      - switch.cable_7
      - switch.cable_8
      - switch.cable_9
      - switch.cable_0
      - switch.cable_ok
    
ifttt:
  key: !secret ifttt_key

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

automation: !include_dir_merge_list automation/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
group: !include_dir_merge_named groups/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
binary_sensor: !include_dir_merge_list binary_sensors/

#BRUH sensors
light:
  - platform: mqtt_json
    name: "Entry LED"
    state_topic: "bruh/entrysensor"
    command_topic: "bruh/entrysensor/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0  
  - platform: mqtt_json
    name: "Office LED"
    state_topic: "bruh/officesensor"
    command_topic: "bruh/officesensor/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0
  - platform: mqtt_json
    name: "Bedroom LED"
    state_topic: "bruh/bedroomsensor"
    command_topic: "bruh/bedroomsensor/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

google_assistant: !include google_assistant.yaml