homeassistant:
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /tmp

default_config:

lovelace:

http:
  ssl_certificate: !secret ssl_cert_loc
  ssl_key: !secret ssl_key_loc

# Discover some devices automatically
discovery:

# Text to speech
tts:
  platform: google_translate
#  language: 'en-us'
  service_name: google_say

#media players
media_player: !include media_players.yaml

#device tracking
device_tracker: !include device_trackers.yaml

influxdb:

recorder:
  # exclude:
  #   domains:
  #   entities:

system_log:
  fire_event: true
logger:
  default: warning
  logs:
    camect: info
    plexwebsocket: fatal
#    homeassistant.components.webhook: debug

notify: !include notify.yaml
automation: !include automations.yaml
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
group: !include_dir_merge_named groups/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
binary_sensor: !include binary_sensors.yaml #!include_dir_merge_list binary_sensors/
light: !include lights.yaml
remote:
  - platform: broadlink
    host: 192.168.1.42
    mac: '78:0F:77:B9:62:85'

climate:
  platform: nest

fan:
  - platform: template
    fans:
      hvac_fan:
        friendly_name: "HVAC Fan"
        value_template: "{{ states('binary_sensor.upstairs_thermostat_fan') }}"
        turn_on:
          service: climate.set_fan_mode
          data:
            entity_id: climate.upstairs
            fan_mode: 'on'
        turn_off:
          service: climate.set_fan_mode
          data:
            entity_id: climate.upstairs
            fan_mode: 'off'
        speeds:

#vendor-specific integrations
ifttt:
  key: !secret ifttt_key
google: #calendar
  client_id: !secret google_oath_client
  client_secret: !secret google_oath_secret
google_assistant: !include google_assistant.yaml
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
      - away
      - online
      - fan
      - is_using_emergency_heat
      - is_locked
      - has_leaf
      - motion_detected
      - person_detected
      - sound_detected
  sensors:
    monitored_conditions:
      - eta
      - security_state
      - humidity
      - temperature

camect: #custom component
  host: !secret camect_host
  port: 443
  username: !secret camect_un
  password: !secret camect_pw
  camera_ids: !secret camect_cameras
#  id: !secret camect_home

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id_peter
      - !secret telegram_id_kelley