homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 87
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

default_config:

lovelace:

http:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert_loc
  ssl_key: !secret ssl_key_loc

# panel_custom:
  # - name: floorplan
    # sidebar_title: Floorplan
    # sidebar_icon: mdi:home
    # url_path: floorplan
    # config: !include floorplan.yaml

# Discover some devices automatically
discovery:

# Text to speech
tts:
  platform: google_translate
  language: 'en-us'
  service_name: google_say

#media players
media_player: !include media_players.yaml

#device tracking
device_tracker: !include device_trackers.yaml

recorder:
  # exclude:
  #   domains:
  #   entities:
  #     - switch.cable_hd
  #     - switch.cable_1
  #     - switch.cable_2
  #     - switch.cable_3
  #     - switch.cable_4
  #     - switch.cable_5
  #     - switch.cable_6
  #     - switch.cable_7
  #     - switch.cable_8
  #     - switch.cable_9
  #     - switch.cable_0
  #     - switch.cable_ok

logger:
  default: warning
  logs:
    camect: error

notify: !include notify.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list automation/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
group: !include_dir_merge_named groups/
script: !include scripts.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_select: !include input_select.yaml
binary_sensor: !include binary_sensors.yaml #!include_dir_merge_list binary_sensors/
light: !include lights.yaml
remote:
  - platform: broadlink
    host: 192.168.1.42
    mac: '78:0F:77:B9:62:85'

climate:
  platform: nest

fan:
  - platform: template
    fans:
      hvac_fan:
        friendly_name: "HVAC Fan"
        value_template: "{{ states('binary_sensor.upstairs_thermostat_fan') }}"
        turn_on:
          service: climate.set_fan_mode
          data:
            entity_id: climate.upstairs
            fan_mode: 'on'
        turn_off:
          service: climate.set_fan_mode
          data:
            entity_id: climate.upstairs
            fan_mode: 'off'
        speeds:

#vendor-specific integrations
ifttt:
  key: !secret ifttt_key
google:
  client_id: !secret google_oath_client
  client_secret: !secret google_oath_secret
google_assistant: !include google_assistant.yaml
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret
  binary_sensors:
    monitored_conditions:
      - away
      - online
      - fan
      - is_using_emergency_heat
      - is_locked
      - has_leaf
      - motion_detected
      - person_detected
      - sound_detected
  sensors:
    monitored_conditions:
      - eta
      - security_state
      - humidity
      - temperature

totalconnect:
  username: !secret tc_user
  password: !secret tc_password
#  code: !secret tc_usercode

camect: #custom component
  host: !secret camect_host
  port: 443
  username: !secret camect_un
  password: !secret camect_pw
  camera_ids: 5634535cb67205fc016d,e2229460a6d9a626be20,5a5056a4b910eb39318d

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret telegram_id_peter
      - !secret telegram_id_kelley