homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 87
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_cert_loc
  ssl_key: !secret ssl_key_loc

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
  platform: google
  language: 'en-us'

mqtt:
  
#media players
media_player:
  - platform: plex

#device tracking
device_tracker:
  - platform: automatic
    client_id: c1ce08e5c7825763112b
    secret: !secret automatic_secret
    username: pae2008@gmail.com
    password: !secret automatic_password
  - platform: nmap_tracker
#    hosts: 192.168.1.28 192.168.1.128
    hosts:
    - 192.168.1.1-30
    - 192.169.1.128
    - 192.168.1.42
    - 192.168.1.200
    home_interval: 5
    scan_options: "-PS135,445 -F --host-timeout 5s"
    exclude:
    - 192.168.1.150
    - 192.168.1.100
    - 192.168.1.101

config:

recorder:
  exclude:
    domains:
    entities:
      - sensor.internet_time
      - sensor.last_boot
      - sensor.since_last_boot
      - sensor.wmata_dc
      - sensor.wmata_md
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary
      - sensor.dark_sky_minutely_summary
      - sensor.time
      - sensor.date
      - sensor.time_utc
      - sensor.time_beat
      - switch.lr_tv_mute
      - switch.lr_tv_cm2
      - switch.lr_tv_hdmi1
      - switch.lr_tv_hdmi2
      - switch.lr_tv_hdmi3
      - switch.lr_tv_hdmi4
      - switch.cable_hd
      - switch.cable_1
      - switch.cable_2
      - switch.cable_3
      - switch.cable_4
      - switch.cable_5
      - switch.cable_6
      - switch.cable_7
      - switch.cable_8
      - switch.cable_9
      - switch.cable_0
      - switch.cable_ok
    
ifttt:
  key: !secret ifttt_key

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

automation: !include_dir_merge_list automation/
zone: !include zones.yaml
sensor: !include_dir_merge_list sensors/
switch: !include switches.yaml
group: !include groups.yaml
script: !include scripts.yaml
#input_boolean: !include input_boolean.yaml
light: !include lights.yaml

emulated_hue:
  listen_port: 80
  exposed_domains:
    - switch
    - script
  off_maps_to_on_domains:
