## BRUH
- platform: mqtt
  schema: json
  name: "Entry LED"
  state_topic: "bruh/entrysensor"
  command_topic: "bruh/entrysensor/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0  
- platform: mqtt
  schema: json
  name: "Office LED"
  state_topic: "bruh/officesensor"
  command_topic: "bruh/officesensor/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
- platform: mqtt
  schema: json
  name: "Bedroom LED"
  state_topic: "bruh/bedroomsensor"
  command_topic: "bruh/bedroomsensor/set"
  brightness: true
  flash: true
  rgb: true
  optimistic: false
  qos: 0
  
## SmartThings
- platform: mqtt
  name: Bedroom Overhead Light
  state_topic: "smartthings/Bedroom Overhead Light/switch"
  command_topic: "smartthings/Bedroom Overhead Light/switch"
  payload_on: "on"
  payload_off: "off"
  brightness: true
  brightness_state_topic: "smartthings/Bedroom Overhead Light/level"
  brightness_command_topic: "smartthings/Bedroom Overhead Light/level"

- platform: mqtt
  name: Living Room Lights
  state_topic: "smartthings/Living Room Lights/switch"
  command_topic: "smartthings/Living Room Lights/switch"
  payload_on: "on"
  payload_off: "off"
  brightness: true
  brightness_state_topic: "smartthings/Living Room Lights/level"
  brightness_command_topic: "smartthings/Living Room Lights/level"

- platform: mqtt
  name: Kitchen Overhead Lights
  state_topic: "smartthings/Kitchen Overhead Lights/switch"
  command_topic: "smartthings/Kitchen Overhead Lights/switch"
  payload_on: "on"
  payload_off: "off"
  brightness: true
  brightness_state_topic: "smartthings/Kitchen Overhead Lights/level"
  brightness_command_topic: "smartthings/Kitchen Overhead Lights/level"