- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max

- platform: speedtest
  monitored_conditions:
    - ping
    - download
    - upload

- platform: broadlink
  host: 192.168.1.42
  mac: 'B4:43:0D:FB:DD:62'
  monitored_conditions:
    - temperature

#- platform: systemmonitor
#  resources:
#    - type: last_boot
#    - type: since_last_boot

#- platform: rest
#  resource: https://api.wmata.com/StationPrediction.svc/json/GetPrediction/A08
#  method: GET
#  headers:
#    api_key: ***REMOVED***
#  value_template: '{{ value_json.trains.destination[0] }}'