title: Home
views:
  - title: Home
    cards:
      - type: picture-glance
        title: Backyard
        entities:
          - camera.backyard
          - binary_sensor.backyard_camera_motion_detected
          - binary_sensor.backyard_camera_person_detected
          - binary_sensor.backyard_camera_sound_detected
          - entity: binary_sensor.backyard_camera_online
            icon: mdi:power
        camera_image: camera.backyard
        show_info: true
        tap_action: dialog
      - type: picture-glance
        title: Front Door
        entities:
          - camera.front_door
          - binary_sensor.front_door_camera_motion_detected
          - binary_sensor.front_door_camera_person_detected
          - binary_sensor.front_door_camera_sound_detected
          - entity: binary_sensor.front_door_camera_online
            icon: mdi:power
        camera_image: camera.front_door
        show_info: true
        tap_action: dialog
      - type: thermostat
        title: Climate
        show_header_toggle: true
        entity: climate.upstairs
      - type: glance
        entities:
          - entity: binary_sensor.home_away
            name: Away?
          - entity: binary_sensor.upstairs_thermostat_fan
            name: Fan
          - entity: sensor.home_security_state
            name: State
      - type: entities
        title: Home Lights
        entities:
          - group.bedroom_lights
          - group.living_room_lights
          - group.office_lights
          - group.dining_room_lights
          - group.patio_lights
          - group.kitchen_lights
      - type: glance
        entities: 
          - entity: calendar.trash
            name: Trash Day
          - entity: calendar.recycle
            name: Recycle Day
      - type: entities
        title: Wake Up
        entities: 
          - sensor.alarm_time
          - group.alarmclock_settings
      - type: entities
        title: WMATA Info
        entities:
          - sensor.wmata_gr_no
          - sensor.wmata_gr_so
          - script.wmata_gr_no
          - script.wmata_gr_so
      - type: entities
        title: Travel Time
        entities:
          - input_select.origin
          - input_select.destination
          - sensor.via_driving
          - sensor.via_metro
          - sensor.via_bus
          
  - title: Security
    icon: mdi:shield
    cards:          
      - type: alarm-panel
        entity: alarm_control_panel.total_connect
      - type: glance
        title: Sensors
        entities:
          - binary_sensor.front_door
          - binary_sensor.back_door
          - binary_sensor.office_window
      - type: glance
        title: Alerts
        entities:
          - binary_sensor.smoke_alarm
          - binary_sensor.co_alarm
          - binary_sensor.half_bath_leak_sensor
          - binary_sensor.kitchen_leak_sensor
          - binary_sensor.master_bath_leak_sensor
          
  - title: Living Room
    icon: mdi:sofa
    cards:
      - type: entities
        entities:
          - group.lr_tv_power
          - switch.cable_power
          - switch.lr_tv_mute
          - input_select.living_room_tv_source
          - input_select.cable_channel
      - type: media-control
        entity: media_player.bedroom_tv
      - type: media-control
        entity: media_player.home_speakers
      - type: media-control
        entity: media_player.kitchen_home
      - type: media-control
        entity: media_player.living_room_speaker
      - type: media-control
        entity: media_player.living_room_tv
      - type: media-control
        entity: media_player.office_speaker

  - title: Sensors
    icon: mdi:led-on
    cards:
      - type: glance
        entities:
          - device_tracker.verizonfiosg1100
          - device_tracker.linksys22446
          - device_tracker.neo
          - device_tracker.surface
          - device_tracker.trinity
          - device_tracker.peter_computer_work
          - device_tracker.kelley_computer_work
          - device_tracker.printer 
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.neo
            tap_action: toggle
          - type: entity-button
            entity: switch.trinity
            tap_action: toggle
          - type: entity-button
            entity: group.office_lights
            tap_action: toggle
      - type: glance
        title: Entry Sensors
        entities:
          - entity: sensor.entry_temperature
            name: Temp
          - entity: sensor.entry_humidity
            name: Humidity
          - entity: sensor.entry_real_feel
            name: Real Feel
          - entity: sensor.entry_ldr
            name: Bright
          - entity: binary_sensor.entry_pir
            name: Motion
          - entity: light.entry_led
            name: LED
      - type: glance
        title: Office Sensors
        entities:
          - entity: sensor.office_temperature
            name: Temp
          - entity: sensor.office_humidity
            name: Humidity
          - entity: sensor.office_real_feel
            name: Real Feel
          - entity: sensor.office_ldr
            name: Bright
          - entity: binary_sensor.office_pir
            name: Motion
          - entity: light.office_led
            name: LED
      - type: glance
        title: Bedroom Sensors
        entities:
          - entity: sensor.bedroom_temperature
            name: Temp
          - entity: sensor.bedroom_humidity
            name: Humidity
          - entity: sensor.bedroom_real_feel
            name: Real Feel
          - entity: sensor.bedroom_ldr
            name: Bright
          - entity: light.bedroom_led
            name: LED
      - type: glance
        title: Bathroom Sensors
        entities:
          - sensor.master_bath_temperature  
          - binary_sensor.master_bath_leak_sensor
          - sensor.half_bath_temperature
          - binary_sensor.half_bath_leak_sensor     
      - type: glance
        title: Kitchen Sensors
        entities:
          - sensor.kitchen_temperature
          - binary_sensor.fridge_door
          - binary_sensor.kitchen_leak_sensor
        
  - title: Weather
    icon: mdi:thermometer
    cards:
      - type: glance
        entities:
          - sun.sun
          - sensor.moon
      - type: entities
        title: Darksky
        entities:
          - sensor.dark_sky_apparent_temperature
          - sensor.dark_sky_cloud_coverage
          - sensor.dark_sky_daily_max_precip_intensity
          - sensor.dark_sky_daily_summary
          - sensor.dark_sky_daytime_high_apparent_temperature
          - sensor.dark_sky_daytime_high_temperature
          - sensor.dark_sky_dew_point
          - sensor.dark_sky_hourly_summary
          - sensor.dark_sky_humidity
          - sensor.dark_sky_icon
          - sensor.dark_sky_minutely_summary
          - sensor.dark_sky_nearest_storm_bearing
          - sensor.dark_sky_nearest_storm_distance
          - sensor.dark_sky_overnight_low_apparent_temperature
          - sensor.dark_sky_overnight_low_temperature
          - sensor.dark_sky_ozone
          - sensor.dark_sky_precip
          - sensor.dark_sky_precip_intensity
          - sensor.dark_sky_precip_probability
          - sensor.dark_sky_pressure
          - sensor.dark_sky_summary
          - sensor.dark_sky_temperature
          - sensor.dark_sky_visibility
          - sensor.dark_sky_wind_bearing
          - sensor.dark_sky_wind_speed
      - type: entities
        title: Weather Underground
        entities:          
          - sensor.pws_alerts
          - sensor.pws_observation_time
          - sensor.pws_solarradiation
          - sensor.pws_uv
          - sensor.pws_visibility_mi
          - sensor.pws_weather_1d
          - sensor.pws_weather_1n
          - sensor.pws_weather_2d
          - sensor.pws_weather_2n
          - sensor.pws_weather_3d
          - sensor.pws_weather_3n
          - sensor.pws_weather_4d
          - sensor.pws_weather_4n

  - title: More
    cards:
      - type: entities
        title: Automations
        show_header_toggle: true
        entities:
          - automation.change_channel
          - automation.change_tv_source
          - automation.computer_on
          - automation.entry_motion
          - automation.goodnight
          - automation.hass_start
          - automation.led_motion
          - automation.led_weather
          - automation.master_alarm
          - automation.media_player_playing
          - automation.office_motion
          - automation.office_motionless
          - automation.plex_wake
          - automation.see_you_later
          - automation.sunrise
          - automation.sunset
          - automation.update_available
          - automation.wake_up
          - automation.weather_alert
      - type: entities
        title: Groups
        show_header_toggle: true
        entities:
          - group.alarmclock
          - group.alarmclock_settings
          - group.all_automations
          - group.all_devices
          - group.all_lights
          - group.all_scripts
          - group.all_switches
          - group.automations
          - group.bedroom_lights
          - group.cable_source
          - group.computers
          - group.darksky
          - group.default_view
          - group.device_status
          - group.devices_kelley
          - group.devices_other
          - group.devices_peter
          - group.dining_room_lights
          - group.entertainment_center
          - group.family
          - group.home_lights
          - group.living_room
          - group.living_room_lights
          - group.lr_tv_power
          - group.lr_tv_source
          - group.nest
          - group.office
          - group.office_lights
          - group.sensor_bathroom
          - group.sensor_bedroom
          - group.sensor_dining_room
          - group.sensor_entry
          - group.sensor_kitchen
          - group.sensor_led
          - group.sensor_office
          - group.sensor_travel
          - group.sensors
          - group.weather
          - group.wmata
          - group.wu
      - type: entities
        title: Sensors
        show_header_toggle: true
        entities:
          - sensor.broadlink_sensor_temperature
          - sensor.date
          - sensor.dining_room_humidity
          - sensor.dining_room_temperature
          - sensor.entry_humidity
          - sensor.entry_ldr
          - sensor.entry_real_feel
          - sensor.entry_temperature
          - sensor.home_eta
          - sensor.home_security_state
          - sensor.internet_time
          - sensor.last_boot
          - sensor.memory_use_percent
          - sensor.processor_use
          - sensor.pushbullet_body
          - sensor.pushbullet_title
          - sensor.since_last_boot
          - sensor.speedtest_download
          - sensor.speedtest_ping
          - sensor.speedtest_upload
          - sensor.time
          - sensor.time_utc
          - sensor.upstairs_thermostat_humidity
          - sensor.upstairs_thermostat_hvac_state
          - sensor.upstairs_thermostat_operation_mode
          - sensor.upstairs_thermostat_target
          - sensor.upstairs_thermostat_temperature