##Entry Sensor
- platform: mqtt  
  state_topic: "bruh/entrysensor"  
  name: "Entry Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
- platform: mqtt  
  state_topic: "bruh/entrysensor"  
  name: "Entry LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
- platform: mqtt  
  state_topic: "bruh/entrysensor"  
  name: "Entry PIR"  
  value_template: '{{ value_json.motion }}'  
- platform: mqtt  
  state_topic: "bruh/entrysensor"  
  name: "Entry Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}' 

##Office Sensor
- platform: mqtt  
  state_topic: "bruh/officesensor"  
  name: "Office Humidity"  
  unit_of_measurement: "%"  
  value_template: '{{ value_json.humidity | round(1) }}'  
- platform: mqtt  
  state_topic: "bruh/officesensor"  
  name: "Office LDR"
  ##This sensor is not calibrated to actual LUX. Rather, this a map of the input voltage ranging from 0 - 1023.
  unit_of_measurement: "LUX"  
  value_template: '{{ value_json.ldr }}'  
- platform: mqtt  
  state_topic: "bruh/officesensor"  
  name: "Office PIR"  
  value_template: '{{ value_json.motion }}'  
- platform: mqtt  
  state_topic: "bruh/officesensor"  
  name: "Office Temperature"  
  unit_of_measurement: "°F"  
  value_template: '{{ value_json.temperature | round(1) }}' 