- platform: time_date
  display_options:
  - 'time'
  - 'date'
  - 'time_utc'
  - 'beat'

- platform: template
  sensors:
    alarm_time:
      friendly_name: 'Time'
      value_template: '{{ "%0.02d:%0.02d" | format(states("input_number.alarmhour") | int, states("input_number.alarmminutes") | int) }}'

- platform: moon

# - platform: speedtest
  # monitored_conditions:
    # - ping
    # - download
    # - upload

# - platform: pushbullet # borked
  # api_key: !secret pushbullet_key
  # monitored_conditions:
    # - title
    # - body

- platform: broadlink
  host: 192.168.1.42
  mac: '78:0F:77:B9:62:85'
  monitored_conditions:
    - temperature

- platform: systemmonitor
  resources:
    - type: last_boot
    - type: memory_use_percent
    - type: processor_use

- platform: uptime
  unit_of_measurement: minutes

- platform: rest
  name: 'WMATA'
  resource: https://api.wmata.com/StationPrediction.svc/json/GetPrediction/E03
  method: GET
  headers:
    api_key: !secret wmata_api
  value_template: '{{ value_json.Trains[0].LocationName }}'
  json_attributes:
    - Trains
  scan_interval: 150

- platform: template
  sensors:
    wmata_gr_no:
      friendly_name: "Green Line Northbound"
      value_template: '
        {% set trains = states.sensor.wmata.attributes.Trains %}
        {% for train in trains if train.DestinationCode == "E10" %}
        {% if loop.first %}{{ train.Min }}
        {% elif loop.last %} and {{ train.Min }}
        {% else %}, {{ train.Min }},
        {% endif %}
        {% endfor %}'
      unit_of_measurement: 'minutes'
    wmata_gr_so:
      friendly_name: "Green Line Southbound"
      value_template: '
        {% set trains = states.sensor.wmata.attributes.Trains %}
        {% for train in trains if train.DestinationCode == "F11" %}
        {% if loop.first %}{{ train.Min }}
        {% elif loop.last %} and {{ train.Min }}
        {% else %}, {{ train.Min }},
        {% endif %}
        {% endfor %}'
      unit_of_measurement: 'minutes'
    washer_power:
        friendly_name: "Washer Power"
        value_template: "{{ state_attr('switch.washer','current_power_w') | default('0') }}"
        unit_of_measurement: "W"
        icon_template: mdi:washing-machine
    dryer_power:
        friendly_name: "Dryer Power"
        value_template: "{{ state_attr('switch.dryer','current_power_w') | default('0') }}"
        unit_of_measurement: "W"
        icon_template: mdi:tumble-dryer