- platform: mqtt
  state_topic: "smartthings/Fridge/temperature"
  name: "Kitchen Temperature"
  unit_of_measurement: "°F"
  
- platform: mqtt
  state_topic: "smartthings/Leeo/temperature"
  name: "Dining Room Temperature"
  unit_of_measurement: "°F"

- platform: mqtt
  state_topic: "smartthings/Leeo/humidity"
  name: "Dining Room Humidity"
  unit_of_measurement: "%"
  device_class: humidity