- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
    
- platform: wunderground
  api_key: !secret wu_api
  monitored_conditions:
    - alerts
    - observation_time
    - weather_1d
    - weather_1n
    - weather_2d
    - weather_2n
    - weather_3d
    - weather_3n
    - weather_4d
    - weather_4n
    - UV
    - visibility_mi
    - solarradiation
    
# - platform: rest
  # name: 'NWS Alerts'
  # resource: https://api.weather.gov/alerts/active/zone/mdz504
  # method: GET
  # headers:
    # User-Agent: 'Home Assistant (https://github.com/epleypa/Home-AssistantConfig)'
  # value_template: '{{ value_json.features|count }}'
  # json_attributes:
    # - title
    # - features