- platform: workday
  country: US
  workdays: [mon,tue,wed,thu,fri]
  excludes: [sat,sun,holiday]
  add_holidays: ['2018-12-24','2018-12-26','2018-12-27','2018-12-28','2018-12-31']

- platform: mqtt
  state_topic: "bruh/entrysensor"
  name: "Entry PIR"
  value_template: '{{ value_json.motion }}'
  payload_on: "motion detected"
  payload_off: "standby"
  device_class: motion
- platform: mqtt
  state_topic: "bruh/officesensor"
  name: "Office PIR"
  value_template: '{{ value_json.motion }}'
  payload_on: "motion detected"
  payload_off: "standby"
  device_class: motion
# - platform: mqtt
  # state_topic: "bruh/bedroomsensor"
  # name: "Bedroom PIR"
  # value_template: '{{ value_json.motion }}'
  # payload_on: "motion_detected"
  # payload_off: "standby"
  # device_class: motion