change_op_mode:
  description: Change the home mode of the camect.
  fields:
    mode:
      description: The new home mode (home or away).
      example: home
disable_camera_alert:
  description: Disable camera(s).
  fields:
    camera:
      description: ID of camera.
      example: 0586c3143fd3db8b0149
enable_camera_alert:
  description: Enable camera(s).
  fields:
    camera:
      description: ID of camera.
      example: 0586c3143fd3db8b0149