- alias: 'LED Motion'
  trigger:
    platform: state
    entity_id: binary_sensor.entry_pir, binary_sensor.office_pir
    to: 'on'
  condition:
    - condition: time
      after: '6:00:00'
      before: '23:00:00'
  action:
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
    - delay: 00:00:01
    - service: light.turn_off
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      
- alias: 'Entry Motion'
  trigger:
    platform: state
    entity_id: binary_sensor.entry_pir
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:00:00'
      - condition: sun
        after: sunset
        before_offset: '-00:15:00'
  action:
    - service: switch.turn_on
      entity_id: group.living_room_lights
    # - service: notify.pushbullet
      # data:
        # message: 'Motion in Entryway'
        
- alias: 'Office Motion'
  trigger:
    platform: state
    entity_id: binary_sensor.office_pir
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:00:00'
      - condition: sun
        after: sunset
        before_offset: '-00:15:00'
  action:
    - service: switch.turn_on
      entity_id: group.office_lights
    # - service: notify.pushbullet
      # data:
        # message: 'Motion in Office'

- alias: 'Office Motionless'
  trigger:
    platform: state
    entity_id: binary_sensor.office_pir
    to: 'off'
    for:
      minutes: 30
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        before_offset: '-00:15:00'
  action:
    - service: switch.turn_off
      entity_id: group.office_lights
    # - service: notify.pushbullet
      # data:
        # message: 'No Motion in Office'