- alias: 'Humidifier'
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state }}'
    - platform: time
      at: '22:00:00'
  action:
    - service_template: > 
        {% if now().strftime('%H:%M:%S') >= '12:00:00' %}switch.turn_on
        {% else %}switch.turn_off
        {% endif %}
      entity_id: switch.bedroom_humidifier
    # - service: notify.pushbullet
      # data_template:
        # title: 'Home Info'
        # message: "It is {{trigger.now}} and the humidifier is 
        # {% if trigger.now.time() >= strptime('12:00:00', '%H:%M:%S').time() %}switch.turn_on
        # {% else %}switch.turn_off
        # {% endif %}."