- alias: Fan On
  trigger:
    - platform: time_pattern
      minutes: '/60'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: home
  action:
    - service: fan.turn_on
      entity_id: fan.hvac_fan
      
