- alias: 'HASS Start'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led, light.office_light, light.storage_light
      data:
        rgb_color: [255,0,0]
    - delay: 
        milliseconds: 500
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led, light.office_light, light.storage_light
      data:
        rgb_color: [0,255,0]
    - delay: 
        milliseconds: 500
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led, light.office_light, light.storage_light
      data:
        rgb_color: [0,0,255]
    - delay: 
        milliseconds: 500
    - service: light.turn_on
      entity_id: light.office_light, light.storage_light
      data:
        color_temp: 369
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      data:
        rgb_color: [255,255,255]
    - delay: 
        milliseconds: 500
    - service: light.turn_off
      entity_id: light.entry_led, light.office_led, light.bedroom_led, light.office_light, light.storage_light

- alias: LED Motion
  trigger:
    platform: state
    entity_id: binary_sensor.livingroom_motion, binary_sensor.bedroom_motion
    to: 'on'
  condition:
  - condition: time
    after: '6:00:00'
    before: '23:00:00'
  action:
  - service: light.turn_on
    entity_id: light.livingroom_led, light.office_led, light.bedroom_led
  - delay: 00:00:01
  - service: light.turn_off
    entity_id: light.livingroom_led, light.office_led, light.bedroom_led

- alias: Motionless
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_motion
      to: 'off'
      for:
        minutes: 60
    - platform: state
      entity_id: binary_sensor.bedroom_motion
      to: 'off'
      for:
        minutes: 20
  action:
    - service: homeassistant.turn_off
      data_template: 
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.bedroom_motion' %}
            group.bedroom_lights
          {% elif trigger.entity_id == 'binary_sensor.livingroom_motion' %}
            group.downstairs_lights
          {% endif %}

- alias: 'Plex Wake'
  trigger:
    - platform: time_pattern
      minutes: '/60'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '18:58:00'
        before: '00:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.neo
    - service: logbook.log
      data:
        name: "Wake Plex"
        message: "has woke Neo"

- alias: 'IFTTT Webhook'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id|lower }}'
      device: '{{ trigger.event.data.device|lower }}'
      command: >
        {% set source = trigger.event.data.command|lower %}
        {% if source == "cable" %}cm2
        {% elif source == "roku" %}hdmi3
        {% elif source == "chromecast" %}hdmi4
        {% elif source == "switch" %}hdmi1
        {% elif source == "xbox" %}hdmi2
        {% endif %}