- alias: 'HASS Start'
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      data:
        rgb_color: [255,0,0]
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      data:
        rgb_color: [0,255,0]
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      data:
        rgb_color: [0,0,255]
    - delay: 00:00:01
    - service: light.turn_on
      entity_id: light.entry_led, light.office_led, light.bedroom_led
      data:
        rgb_color: [255,255,255]
    - delay: 00:00:01
    - service: light.turn_off
      entity_id: light.entry_led, light.office_led, light.bedroom_led

- alias: 'Plex Wake'
  trigger:
    - platform: time_pattern
      minutes: '/60'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '18:58:00'
        before: '00:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.neo
    - service: logbook.log
      data:
        name: "Wake Plex"
        message: "has woke Neo"

- alias: 'IFTTT Webhook'
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'