- alias: "NextTrain_DC"
  trigger:
    - platform: state
      entity_id: input_boolean.wmata_dc
      state: 'on'
  action:
    - service: tts.google_say
      data_template:
        cache: false
        entity_id: media_player.google_home
        message: "the next metro train leaves for DC from friendship heights in {{ states('sensor.wmata_dc') }} minutes"
    - service: input_boolean.turn_off
      entity_id: input_boolean.wmata_dc
        
- alias: "NextTrain_MD"
  trigger:
    - platform: state
      entity_id: input_boolean.wmata_md
      state: 'on'
  action:
    - service: tts.google_say
      data_template:
        cache: false
        entity_id: media_player.google_home
        message: "the next metro train leaves for Maryland from friendship heights in {{ states('sensor.wmata_md') }} minutes"
    - service: input_boolean.turn_off
      entity_id: input_boolean.wmata_md