- alias: 'Sunrise'
  trigger:
    platform: sun
    event: sunrise
#    offset: '+00:15:00'
  action:
    - service: notify.pushbullet
      data:
        message: 'The sun is up.'
    # - service: switch.turn_off
      # entity_id: group.home_lights
    - service: light.turn_off
      entity_id: light.leeo
    - service: switch.turn_off
      entity_id: switch.bedroom_humidifier

# - alias: 'Get Up'
  # trigger:
    # platform: time
    # at: '07:00:00'
  # condition:
    # condition: and
    # conditions:
      # # - condition: state
        # # entity_id: sun.sun
        # # state: 'below_horizon'
      # - condition: time
        # weekday:
          # - mon
          # - tue
          # - wed
          # - thu
          # - fri
  # action:
    # - service: switch.turn_on
      # entity_id: group.home_lights
    # - service: notify.pushbullet
      # data:
        # message: 'Time to start the day!'

- alias: 'Wake Up'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.alarm_time.state }}'
  condition:
    condition: or
    conditions:
      - condition: and
        conditions:
          - condition: state
            entity_id: input_boolean.alarmweekday
            state: 'on'
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
      - condition: state
        entity_id: input_boolean.alarmweekday
        state: 'off'
  action:
    - service: switch.turn_on
      entity_id: switch.bedroom_peter_light
    - service: notify.pushbullet
      data:
        message: 'Time to start the day!'
    - delay: 00:45:00
    - service: switch.turn_off
      entity_id: switch.bedroom_peter_light

- alias: 'See You Later'
  trigger:
    - platform: state
      entity_id: group.family
      to: 'not_home'
      for:
        minutes: 10
    - platform: state
      entity_id: alarm_control_panel.total_connect
      to: 'armed_home'
    - platform: state
      entity_id: alarm_control_panel.total_connect
      to: 'armed_away'
  # condition:
    # condition: or
    # conditions:
      # - condition: time
        # after: '08:00:00'
        # before: '10:00:00'
      # - condition: sun
        # after: sunset
        # after_offset: '-00:30:00'
  action:
    - service: homeassistant.turn_off
      entity_id: group.home_lights
    - service: notify.pushbullet
      data:
       message: 'See you later!'

- alias: 'Welcome Home'
  trigger:
   # platform: state
   # entity_id: group.family
   # from: 'not_home'
   # to: 'home'
   # for:
     # minutes: 10
    - platform: state
      entity_id: alarm_control_panel.total_connect
      to: 'disarmed'
  condition:
    condition: sun
    after: sunset
    after_offset: '-00:30:00'
  action:
    - service: switch.turn_on
      entity_id: group.living_room_lights
    - service: notify.pushbullet
      data:
        message: 'Welcome Home!'

- alias: 'Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:15:00'
  # condition:
    # condition: and
    # conditions:
      # - condition: state
        # entity_id: group.family
        # state: 'home'
      # - condition: time
        # before: '22:00:00'
  action:
    - service: notify.pushbullet
      data:
        message: 'The sun is down.'
    # - service: switch.turn_on
      # entity_id: group.home_lights
    - service: light.turn_on
      entity_id: light.leeo

- alias: 'Goodnight'
  trigger:
    platform: time
    at: '23:05:00'
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
  action:
    - service: homeassistant.turn_off
      entity_id: group.home_lights
    - service: notify.pushbullet
      data:
        message: 'Goodnight!'
    - service: switch.turn_on
      entity_id: switch.bedroom_humidifier