- alias: 'Change TV Source'
  trigger:
    platform: state
    entity_id: input_select.living_room_tv_source
  action:
    - service: switch.turn_on
      data_template:
        entity_id: >-
            {% set source = states.input_select.living_room_tv_source.state | lower %}
            {% if source == "cable" %}switch.lr_tv_cm2
            {% elif source == "roku" %}switch.lr_tv_hdmi3
            {% elif source == "chromecast" %}switch.lr_tv_hdmi4
            {% elif source == "switch" %}switch.lr_tv_hdmi1
            {% elif source == "xbox" %}switch.lr_tv_hdmi2
            {% endif %}

- alias: Change Channel
  trigger: 
    - platform: state
      entity_id: input_select.cable_channel
  action:
    - service: switch.turn_on
      data_template:
        entity_id: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          switch.cable_{{ indexes[0] | int }}
    - condition: template
      value_template: >
        {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        {{ indexes | count >= 2 }}
    - delay:
        milliseconds: 500
    - service: switch.turn_on
      data_template:
        entity_id: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          switch.cable_{{ indexes[1] | int }}
    - condition: template
      value_template: >
        {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        {{ indexes | count >= 3 }}
    - delay:
        milliseconds: 500
    - service: switch.turn_on
      data_template:
        entity_id: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          switch.cable_{{ indexes[2] | int }}
# - alias: Change Channel
  # trigger: 
    # - platform: state
      # entity_id: input_select.tv_kanaler_stuen
  # action:
    # - service: switch.broadlink_send_packet_10_0_0_116
      # data_template:
        # packet: >
          # {% set numbers = [ 'JgDSAJOVETgRORE4ERQRFBETERQRFBE4ETkROBEUERQRExEUERQROBEUERQRExI4ERQRExITERQROBE5ETgRFBE4EjgROBEABgGTlBI4ETgROREUERMRFBEUERQROBE4EjgRFBETEhMRFBEUETgRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgRAAYBk5QSOBE4EjUUFBETERQRFBEUETgROBI4ERQRExEUERQRFBE4ERQRExITETkRExEUERQRFBE4ETgSOBEUETgRORE4EQANBQAAAAAAAA==', 'JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETYUOBEUERQRExEUERQRFBETETkRExITERQRFBETETkROBEUETgRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBE5ETgRFBEUERMSExEUERQRExE5ERMSExEUERQRExI4ETgRFBE4EjgROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOUETkROBE5ERMRFBEUERQRExE5ETgRORETEhMRFBETEhMRORETETkRFBETERQRFBETEhMRORETEjgROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExEUERQRExITETkRExI4ERQRExEUERQRExITETkRExI4ETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOVETgROBI4ERQRExEUERQRFBE4ETgSOBEUERMRFBEUERMSExE5ETgRFBEUERMRFBEUETgRFBEUETgROBI4ETgSOBEABgCTlRE4ETgSOBEUERMRFBEUERQROBE5ETgRFBETEhMRFBEUERMRORE4ERQRFBETEhMRFBE4EhMRFBE4ETkROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJKVETkROBE5ERMRFBEUERMSExE5ETgRORETERQRFBETEhMRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgROREABgCTlBI4ETgROREUERMRFBEUERMSOBE4ETkRFBETERQRFBETEhMRFBEUETgRFBEUERMRFBE4EjgROBITETkROBE4EjgRAA0FAAAAAAAAAAAAAAAA==','JgDSAJOUEjgROBE5ERQRExITERQRExI4ETgROREUERMRFBEUERMSOBEUERMROREUERMRFBEUERMSOBE4EhMRORE4ETgSOBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUETgRFBEUETgRFBEUERMSExEUETYTOREUETgROBI4ETgSAAYAk5UROBE5ETgRFBEUERMRFBEUETgRORE4ERQRFBETERQRFBE4ERQRFBE4ERQRFBETEhMRFBE4EjgRFBE4ETgSOBE4EgANBQAAAAAAAA==', 'JgCMAJOUEjgROBE5ERQRExEUERQRExI4ETgROREUERMRFBEUERMSExE5ERMROREUERMRFBEUETgRFBE4EhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUERQROBEUETgRFBEUERQRExE5ERMSNhMUETgRORE4ETgSAA0FAAAAAAAAAAAAAAAA==','JgCMAJOUEjgROBI4ERQRExEUERQRExI4ETgSOBEUERMRFBEUERQROBEUETgRORETERQRFBEUERMRORETEhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBI4ETgRFBEUERQRExEUETgSExE5ETgRFBEUERMRFBEUETgRFBEUETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==','JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETkROBEUERQRExITERQRFBE4ETkROBEUERMSExEUETgSExEUERQROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExITERQRFBETERQROBI4ETgSExEUERQRExE5ERMSExEUETgSOBE4EjgRAA0FAAAAAAAAAAAAAAAA=='] %}
          # {% set indexes = states.input_select.tv_kanaler_stuen.state.split(' ')[0] %}
          # {{ numbers[indexes[0] | int] }}
    # - condition: template
      # value_template: >
        # {% set indexes = states.input_select.tv_kanaler_stuen.state.split(' ')[0] %}
        # {{ indexes | count >= 2 }}
    # - delay:
        # seconds: 1
    # - service: switch.broadlink_send_packet_10_0_0_116
      # data_template:
        # packet: >
          # {% set numbers = [ 'JgDSAJOVETgRORE4ERQRFBETERQRFBE4ETkROBEUERQRExEUERQROBEUERQRExI4ERQRExITERQROBE5ETgRFBE4EjgROBEABgGTlBI4ETgROREUERMRFBEUERQROBE4EjgRFBETEhMRFBEUETgRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgRAAYBk5QSOBE4EjUUFBETERQRFBEUETgROBI4ERQRExEUERQRFBE4ERQRExITETkRExEUERQRFBE4ETgSOBEUETgRORE4EQANBQAAAAAAAA==', 'JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETYUOBEUERQRExEUERQRFBETETkRExITERQRFBETETkROBEUETgRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBE5ETgRFBEUERMSExEUERQRExE5ERMSExEUERQRExI4ETgRFBE4EjgROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOUETkROBE5ERMRFBEUERQRExE5ETgRORETEhMRFBETEhMRORETETkRFBETERQRFBETEhMRORETEjgROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExEUERQRExITETkRExI4ERQRExEUERQRExITETkRExI4ETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOVETgROBI4ERQRExEUERQRFBE4ETgSOBEUERMRFBEUERMSExE5ETgRFBEUERMRFBEUETgRFBEUETgROBI4ETgSOBEABgCTlRE4ETgSOBEUERMRFBEUERQROBE5ETgRFBETEhMRFBEUERMRORE4ERQRFBETEhMRFBE4EhMRFBE4ETkROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJKVETkROBE5ERMRFBEUERMSExE5ETgRORETERQRFBETEhMRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgROREABgCTlBI4ETgROREUERMRFBEUERMSOBE4ETkRFBETERQRFBETEhMRFBEUETgRFBEUERMRFBE4EjgROBITETkROBE4EjgRAA0FAAAAAAAAAAAAAAAA==','JgDSAJOUEjgROBE5ERQRExITERQRExI4ETgROREUERMRFBEUERMSOBEUERMROREUERMRFBEUERMSOBE4EhMRORE4ETgSOBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUETgRFBEUETgRFBEUERMSExEUETYTOREUETgROBI4ETgSAAYAk5UROBE5ETgRFBEUERMRFBEUETgRORE4ERQRFBETERQRFBE4ERQRFBE4ERQRFBETEhMRFBE4EjgRFBE4ETgSOBE4EgANBQAAAAAAAA==', 'JgCMAJOUEjgROBE5ERQRExEUERQRExI4ETgROREUERMRFBEUERMSExE5ERMROREUERMRFBEUETgRFBE4EhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUERQROBEUETgRFBEUERQRExE5ERMSNhMUETgRORE4ETgSAA0FAAAAAAAAAAAAAAAA==','JgCMAJOUEjgROBI4ERQRExEUERQRExI4ETgSOBEUERMRFBEUERQROBEUETgRORETERQRFBEUERMRORETEhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBI4ETgRFBEUERQRExEUETgSExE5ETgRFBEUERMRFBEUETgRFBEUETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==','JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETkROBEUERQRExITERQRFBE4ETkROBEUERMSExEUETgSExEUERQROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExITERQRFBETERQROBI4ETgSExEUERQRExE5ERMSExEUETgSOBE4EjgRAA0FAAAAAAAAAAAAAAAA=='] %}
          # {% set indexes = states.input_select.tv_kanaler_stuen.state.split(' ')[0] %}
          # {{ numbers[indexes[1] | int] }} 
    # - condition: template
      # value_template: >
        # {% set indexes = states.input_select.tv_kanaler_stuen.state.split(' ')[0] %}
        # {{ indexes | count >= 3 }}
    # - delay:
        # seconds: 1
    # - service: switch.broadlink_send_packet_10_0_0_116
      # data_template:
        # packet: >
          # {% set numbers = [ 'JgDSAJOVETgRORE4ERQRFBETERQRFBE4ETkROBEUERQRExEUERQROBEUERQRExI4ERQRExITERQROBE5ETgRFBE4EjgROBEABgGTlBI4ETgROREUERMRFBEUERQROBE4EjgRFBETEhMRFBEUETgRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgRAAYBk5QSOBE4EjUUFBETERQRFBEUETgROBI4ERQRExEUERQRFBE4ERQRExITETkRExEUERQRFBE4ETgSOBEUETgRORE4EQANBQAAAAAAAA==', 'JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETYUOBEUERQRExEUERQRFBETETkRExITERQRFBETETkROBEUETgRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBE5ETgRFBEUERMSExEUERQRExE5ERMSExEUERQRExI4ETgRFBE4EjgROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOUETkROBE5ERMRFBEUERQRExE5ETgRORETEhMRFBETEhMRORETETkRFBETERQRFBETEhMRORETEjgROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExEUERQRExITETkRExI4ERQRExEUERQRExITETkRExI4ETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJOVETgROBI4ERQRExEUERQRFBE4ETgSOBEUERMRFBEUERMSExE5ETgRFBEUERMRFBEUETgRFBEUETgROBI4ETgSOBEABgCTlRE4ETgSOBEUERMRFBEUERQROBE5ETgRFBETEhMRFBEUERMRORE4ERQRFBETEhMRFBE4EhMRFBE4ETkROBE5ETgRAA0FAAAAAAAAAAAAAAAA==', 'JgCMAJKVETkROBE5ERMRFBEUERMSExE5ETgRORETERQRFBETEhMRFBEUERMROREUERMRFBEUETgRORE4ERQROBE5ETgROREABgCTlBI4ETgROREUERMRFBEUERMSOBE4ETkRFBETERQRFBETEhMRFBEUETgRFBEUERMRFBE4EjgROBITETkROBE4EjgRAA0FAAAAAAAAAAAAAAAA==','JgDSAJOUEjgROBE5ERQRExITERQRExI4ETgROREUERMRFBEUERMSOBEUERMROREUERMRFBEUERMSOBE4EhMRORE4ETgSOBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUETgRFBEUETgRFBEUERMSExEUETYTOREUETgROBI4ETgSAAYAk5UROBE5ETgRFBEUERMRFBEUETgRORE4ERQRFBETERQRFBE4ERQRFBE4ERQRFBETEhMRFBE4EjgRFBE4ETgSOBE4EgANBQAAAAAAAA==', 'JgCMAJOUEjgROBE5ERQRExEUERQRExI4ETgROREUERMRFBEUERMSExE5ERMROREUERMRFBEUETgRFBE4EhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExEUERQROBE5ETgRFBEUERMSExEUERQROBEUETgRFBEUERQRExE5ERMSNhMUETgRORE4ETgSAA0FAAAAAAAAAAAAAAAA==','JgCMAJOUEjgROBI4ERQRExEUERQRExI4ETgSOBEUERMRFBEUERQROBEUETgRORETERQRFBEUERMRORETEhMRORE4ETkROBEABgCTlRE4ETkROBEUERQRExITERQROBI4ETgRFBEUERQRExEUETgSExE5ETgRFBEUERMRFBEUETgRFBEUETgRORE4ETkRAA0FAAAAAAAAAAAAAAAA==','JgCMAJOVETgRORE4ERQRFBETEhMRFBE4ETkROBEUERQRExITERQRFBE4ETkROBEUERMSExEUETgSExEUERQROBE5ETgROBIABgCTlBE5ETgRORETERQRFBEUERMRORE4ETkRExITERQRFBETERQROBI4ETgSExEUERQRExE5ERMSExEUETgSOBE4EjgRAA0FAAAAAAAAAAAAAAAA=='] %}
          # {% set indexes = states.input_select.tv_kanaler_stuen.state.split(' ')[0] %}
          # {{ numbers[indexes[2] | int] }} 