- alias: 'Change TV Source'
  trigger:
    platform: state
    entity_id: input_select.living_room_tv_source
  action:
    - service: remote.send_command
      data_template:
        entity_id: remote.broadlink
        device: television
        command: >-
          {% set source = states('input_select.living_room_tv_source') | lower %}
          {% if source == "cable" %}cm2
          {% elif source == "roku" %}hdmi3
          {% elif source == "chromecast" %}hdmi4
          {% elif source == "switch" %}hdmi1
          {% elif source == "xbox" %}hdmi2
          {% endif %}

- alias: Change Channel
  trigger: 
    - platform: state
      entity_id: input_select.cable_channel
  action:
    - service: remote.send_command
      data_template:
        entity_id: remote.broadlink
        device: cable
        command: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          {{ indexes[0] | int }}
    - condition: template
      value_template: >
        {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        {{ indexes | count >= 2 }}
    - delay:
        milliseconds: 500
    - service: remote.send_command
      data_template:
        entity_id: remote.broadlink
        device: cable
        command: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          {{ indexes[1] | int }}
    - condition: template
      value_template: >
        {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        {{ indexes | count >= 3 }}
    - delay:
        milliseconds: 500
    - service: remote.send_command
      data_template:
        entity_id: remote.broadlink
        device: cable
        command: >
          {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          {{ indexes[2] | int }}



# - alias: 'Change TV Source' #Archived
  # trigger:
    # platform: state
    # entity_id: input_select.living_room_tv_source
  # action:
    # - service: switch.turn_on
      # data_template:
        # entity_id: >-
            # {% set source = states('input_select.living_room_tv_source') | lower %}
            # {% if source == "cable" %}switch.lr_tv_cm2
            # {% elif source == "roku" %}switch.lr_tv_hdmi3
            # {% elif source == "chromecast" %}switch.lr_tv_hdmi4
            # {% elif source == "switch" %}switch.lr_tv_hdmi1
            # {% elif source == "xbox" %}switch.lr_tv_hdmi2
            # {% endif %}

# - alias: Change Channel #Archived
  # trigger: 
    # - platform: state
      # entity_id: input_select.cable_channel
  # action:
    # - service: switch.turn_on
      # data_template:
        # entity_id: >
          # {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          # switch.cable_{{ indexes[0] | int }}
    # - condition: template
      # value_template: >
        # {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        # {{ indexes | count >= 2 }}
    # - delay:
        # milliseconds: 500
    # - service: switch.turn_on
      # data_template:
        # entity_id: >
          # {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          # switch.cable_{{ indexes[1] | int }}
    # - condition: template
      # value_template: >
        # {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
        # {{ indexes | count >= 3 }}
    # - delay:
        # milliseconds: 500
    # - service: switch.turn_on
      # data_template:
        # entity_id: >
          # {% set indexes = states.input_select.cable_channel.state.split(' ')[0] %}
          # switch.cable_{{ indexes[2] | int }}