- alias: "Weather Alert"
  trigger:
    - platform: numeric_state
      entity_id: sensor.pws_alerts
      above: 0
  action:
    - service: notify.pushbullet
      data_template:
        message: 'Weather Alert: {{ states.sensor.pws_alerts.attributes.Description }}'

- alias: "LED Weather"
  trigger:
    - platform: state
      entity_id: sensor.dark_sky_icon
  action:
    - service: light.turn_on
      entity_id: light.livingroom_led, light.office_led, light.bedroom_led
      data_template: 
        color_name: >-
          {% if "clear" in states.sensor.dark_sky_icon.state %}yellow
          {%-elif "cloudy" in states.sensor.dark_sky_icon.state %}purple
          {%-elif "overcast" in states.sensor.dark_sky_icon.state %}purple
          {%-elif "fog" in states.sensor.dark_sky_icon.state %}blue
          {%-elif "rain" in states.sensor.dark_sky_icon.state %}blue
          {%-elif "wind" in states.sensor.dark_sky_icon.state %}cyan
          {%-elif "ice" in states.sensor.dark_sky_icon.state %}cyan
          {%-elif "snow" in states.sensor.dark_sky_icon.state %}cyan
          {%-elif "thunderstorm" in states.sensor.dark_sky_icon.state %}red
          {%-elif "hail" in states.sensor.dark_sky_icon.state %}cyan
          {%-elif "tornado" in states.sensor.dark_sky_icon.state %}red
          {%-else %}white
          {% endif %}
    - service: light.turn_off
      entity_id: light.livingroom_led, light.office_led, light.bedroom_led
